confirm_os_window_close 0
# background #000000
# foreground #ff9d26
# cursor #ff8c00

window_padding_width 10
hide_window_decorations yes
tab_bar_style hidden
window_border_width 1pt
# active_border_color #ff8c00
# inactive_border_color #282828
window_margin_width 1
# color1 #ff8c00
# color9 #ff4500



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
include ~/.cache/noctalia/colors-kitty.conf
background_opacity 0.6
dynamic_background_opacity yes
modify_font line_height -4
background_blur 1
