color0 #171213
color1 #ffb4ab
color2 #ffb1c3
color3 #e3bdc4
color4 #edbd92
color5 #ffb1c3
color6 #e3bdc4
color7 #ece0e1
color8 #9e8c8f
color9 #ffb4ab
color10 #ffb1c3
color11 #e3bdc4
color12 #edbd92
color13 #ffb1c3
color14 #e3bdc4
color15 #ece0e1

cursor                #ece0e1
cursor_text_color     #171213
background            #171213
foreground            #ece0e1
selection_foreground  #d6c2c5
selection_background  #514346
active_border_color   #ffb1c3
inactive_border_color #514346
url_color             #ffb1c3

active_tab_foreground   #5e112e
active_tab_background   #ffb1c3
inactive_tab_foreground #d6c2c5
inactive_tab_background #514346
cursor_trail_color      #d6c2c5
